CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR(100)
);
-- 수정 = 삭제 + 생성
-- 테이블 삭제
-- ORA-00942: table or view does not exist
DROP TABLE STUDENT_TBL;

-- TABLE에 데이터를 넣는 방법! -> 회원가입
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('일용자', 22, 1, '서울');

--컬럼명 생략 가능!
INSERT INTO STUDENT_TBL
VALUES('이용자', 23, 2, '서울시 종로구');

INSERT INTO STUDENT_TBL
VALUES('삼용자', 33, 3, '경기도 동두천');

INSERT INTO STUDENT_TBL
VALUES('사용자', 44, 4, '제주특별자치도 제주시');

INSERT INTO STUDENT_TBL
VALUES(' ', 55, 5, NULL);

-- 데이터를 삭제해보자 -> 회원탈퇴
DELETE FROM STUDENT_TBL;

UPDATE STUDENT_TBL
SET STUDENT_AGE = 99;
--WHERE STUDENT_GRADE = 2;

DELETE FROM STUDENT_TBL
WHERE STUDENT_GRADE = 4;

CREATE TABLE DATATYPE_TBL(
    MOONJJA CHAR(10),
    -- 알파벳 10글자 한글 3글자
    MOONJJAYUL VARCHAR2(100),
    -- 알파벳 100글자 한글 33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP
);

DROP TABLE DATATYPE_TBL;

DESC DATATYPE_TBL;

DELETE FROM DATATYPE_TBL
WHERE SOOJJA = 22;

INSERT INTO DATATYPE_TBL VALUES('문자1', '문자열1', 11, SYSDATE, SYSTIMESTAMP);
INSERT INTO DATATYPE_TBL VALUES('문자2', '문자열2', 22, SYSDATE, SYSTIMESTAMP);
INSERT INTO DATATYPE_TBL VALUES('문자3', '문자열3', 33, SYSDATE, SYSTIMESTAMP);
INSERT INTO DATATYPE_TBL VALUES('문자4', '문자열4', 44, SYSDATE, SYSTIMESTAMP);

SELECT MOONJJA,  MOONJJAYUL, SOOJJA, NALJJA, NALJJA2
FROM DATATYPE_TBL;

UPDATE DATATYPE_TBL
SET MOONJJAYUL = '오라클'
WHERE SOOJJA = 33;




-- 데이터 조회
-- FROM -> WHERE -> SELECT
SELECT STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS
FROM STUDENT_TBL;
--WHERE STUDENT_GRADE = 2;
